-- =====================================================================
-- Debia Smart Inventory — esquema PostgreSQL (Supabase)
--
-- Ejecutar UNA vez sobre una base vacía (Supabase → SQL Editor → pegar
-- y "Run"). Es idempotente en lo posible: se puede volver a ejecutar sin
-- perder datos.
--
-- Seguridad:
--   * Las tablas viven en el esquema "inventario", NO en "public". La API
--     REST automática de Supabase (PostgREST) solo publica los esquemas
--     listados en "Exposed schemas" (por defecto public y graphql_public),
--     así que estas tablas no quedan accesibles desde internet con la
--     clave "anon". No agregues "inventario" a esa lista.
--   * Además se activa Row Level Security (RLS) en todas las tablas sin
--     políticas para anon/authenticated: aunque alguien expusiera el
--     esquema por error, esos roles no verían ni modificarían nada.
--   * El dueño de las tablas (postgres) no está sujeto a RLS. Si la app
--     se conecta con un rol propio de mínimo privilegio, ejecutar después
--     database/rol_aplicacion.sql.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS inventario;
SET search_path TO inventario;

-- ---------------------------------------------------------------------
-- Usuarios de la aplicación
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuarios (
    id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                varchar(100) NOT NULL,
    usuario               varchar(50)  NOT NULL,
    -- Forma en minúsculas: impide "Admin" y "admin" como cuentas distintas.
    usuario_normalizado   varchar(50)  GENERATED ALWAYS AS (lower(usuario)) STORED,
    correo                varchar(100),
    numero_identificacion varchar(50),
    contrasena            varchar(255) NOT NULL,
    rol                   varchar(10)  NOT NULL CHECK (rol IN ('ADMIN', 'USUARIO')),
    -- Permisos asignados por la cuenta principal (App\Dominio\Permiso).
    -- La cuenta principal (App\Config::CORREO_CUENTA_PRINCIPAL) los tiene
    -- todos sin importar este valor.
    permisos              text[]       NOT NULL DEFAULT '{}',
    activo                boolean      NOT NULL DEFAULT true,
    fecha_creacion        timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT usuarios_usuario_unico UNIQUE (usuario),
    CONSTRAINT usuarios_usuario_normalizado_unico UNIQUE (usuario_normalizado),
    CONSTRAINT usuarios_permisos_validos CHECK (
        permisos <@ ARRAY['EDITAR_EQUIPO', 'CREAR_USUARIO', 'EDITAR_USUARIO', 'CAMBIAR_CONTRASENA']::text[]
    )
);

-- ---------------------------------------------------------------------
-- Inventario de equipos
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS equipos (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo           varchar(10),
    marca          varchar(20),
    identificador  varchar(50),
    asignado_a     varchar(100),
    serial         varchar(100),
    procesador     varchar(100),
    ram            varchar(20),
    disco          varchar(50),
    disco2         varchar(50),
    estado         varchar(20) DEFAULT 'Activo'
                   CHECK (estado IN ('Activo', 'Bodega', 'En reparación', 'Dado de baja')),
    ubicacion      varchar(100),
    codigo_barras  varchar(100),
    fecha_registro timestamptz NOT NULL DEFAULT now()
);

-- Único sin distinguir mayúsculas (como lo hacía MySQL): "abc1" y "ABC1"
-- son el mismo código.
CREATE UNIQUE INDEX IF NOT EXISTS equipos_codigo_barras_unico ON equipos (upper(codigo_barras));
CREATE INDEX IF NOT EXISTS equipos_identificador_idx ON equipos (identificador);

-- ---------------------------------------------------------------------
-- Mantenimientos (preventivos y correctivos)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mantenimientos (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipo_id          integer NOT NULL REFERENCES equipos (id) ON DELETE CASCADE,
    fecha              date    NOT NULL,
    tipo_mantenimiento varchar(15) NOT NULL CHECK (tipo_mantenimiento IN ('Preventivo', 'Correctivo')),
    responsable        varchar(100),
    descripcion        text,
    estado             varchar(20) DEFAULT 'Activo'
                       CHECK (estado IN ('Activo', 'En reparación', 'Finalizado')),
    observaciones      text,
    fecha_creacion     timestamptz NOT NULL DEFAULT now()
);

-- PostgreSQL no indexa las claves foráneas automáticamente.
CREATE INDEX IF NOT EXISTS mantenimientos_equipo_idx ON mantenimientos (equipo_id);
CREATE INDEX IF NOT EXISTS mantenimientos_tipo_fecha_idx ON mantenimientos (tipo_mantenimiento, fecha DESC);

-- ---------------------------------------------------------------------
-- Repuestos usados en los mantenimientos
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS repuestos (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         varchar(100) NOT NULL,
    tipo           varchar(50),
    capacidad      varchar(50),
    serial         varchar(100),
    descripcion    text,
    valor          numeric(10, 2),
    stock          integer DEFAULT 0,
    estado         varchar(15) DEFAULT 'Disponible' CHECK (estado IN ('Disponible', 'Agotado')),
    fecha_registro timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT repuestos_serial_unico UNIQUE (serial)
);

CREATE TABLE IF NOT EXISTS mantenimiento_repuestos (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mantenimiento_id integer NOT NULL REFERENCES mantenimientos (id) ON DELETE CASCADE,
    repuesto_id      integer NOT NULL REFERENCES repuestos (id) ON DELETE CASCADE,
    cantidad         integer DEFAULT 1,
    valor_unitario   numeric(10, 2) NOT NULL,
    fecha_registro   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS mantenimiento_repuestos_mantenimiento_idx ON mantenimiento_repuestos (mantenimiento_id);
CREATE INDEX IF NOT EXISTS mantenimiento_repuestos_repuesto_idx ON mantenimiento_repuestos (repuesto_id);

-- ---------------------------------------------------------------------
-- Bitácora de acciones
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS logs_sistema (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id integer REFERENCES usuarios (id) ON DELETE SET NULL,
    accion     varchar(100),
    detalle    text,
    fecha      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS logs_sistema_usuario_idx ON logs_sistema (usuario_id);

-- ---------------------------------------------------------------------
-- Intentos de login fallidos (protección contra fuerza bruta).
-- "identificador" es un hash SHA-256, no el usuario ni la IP en claro.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS intentos_login (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identificador   varchar(150) NOT NULL,
    intentos        integer      NOT NULL DEFAULT 1,
    primer_intento  timestamptz  NOT NULL,
    ultimo_intento  timestamptz  NOT NULL,
    bloqueado_hasta timestamptz,
    CONSTRAINT intentos_login_identificador_unico UNIQUE (identificador)
);

-- ---------------------------------------------------------------------
-- Row Level Security en todas las tablas y sin acceso para los roles
-- de la API de Supabase (los bloques DO no fallan si esos roles no
-- existen, p. ej. en un PostgreSQL local de desarrollo).
-- ---------------------------------------------------------------------
ALTER TABLE usuarios                ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipos                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE mantenimientos          ENABLE ROW LEVEL SECURITY;
ALTER TABLE repuestos               ENABLE ROW LEVEL SECURITY;
ALTER TABLE mantenimiento_repuestos ENABLE ROW LEVEL SECURITY;
ALTER TABLE logs_sistema            ENABLE ROW LEVEL SECURITY;
ALTER TABLE intentos_login          ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
    rol_api text;
BEGIN
    FOREACH rol_api IN ARRAY ARRAY['anon', 'authenticated'] LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = rol_api) THEN
            EXECUTE format('REVOKE ALL ON SCHEMA inventario FROM %I', rol_api);
            EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA inventario FROM %I', rol_api);
            EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA inventario FROM %I', rol_api);
        END IF;
    END LOOP;
END
$$;
